categories:
  Newsletter:
    label: 'Newsletter'
  Newsletter.templates:
    label: 'Templates'
    parent: Newsletter
  Newsletter.pages:
    label: 'Pages'
    parent: Newsletter
  Newsletter.layout:
    label: 'Layout'
    parent: Newsletter
  Newsletter.settings:
    label: 'Settings'
    parent: Newsletter

settings:
  newsletter.templateRootPath:
    label: 'Templates'
    category: Newsletter.templates
    description: 'Path to template root'
    type: string
    default: 'EXT:sitepackage/Resources/Private/Components/Templates/Newsletter/'
  newsletter.partialRootPath:
    label: 'Partials'
    category: Newsletter.templates
    description: 'Path to partial root'
    type: string
    default: 'EXT:sitepackage/Resources/Private/Components/Partials/Newsletter/'
  newsletter.layoutRootPath:
    label: 'Layouts'
    category: Newsletter.templates
    description: 'Path to layout root'
    type: string
    default: 'EXT:sitepackage/Resources/Private/Components/Layouts/Newsletter/'
  newsletter.storagePid:
    label: 'Default storage PID'
    category: Newsletter.pages
    description: 'Folder that stores all blogs, blog-posts and comments'
    type: int
    default: 2
