categories:
  Events:
    label: 'Events'
  Events.templates:
    label: 'Templates'
    parent: Events
  Events.pages:
    label: 'Pages'
    parent: Events
  Events.layout:
    label: 'Layout'
    parent: Events
  Events.settings:
    label: 'Settings'
    parent: Events

settings:
  events.templateRootPath:
    label: 'Templates'
    category: Events.templates
    description: 'Path to template root'
    type: string
    default: 'EXT:sitepackage/Resources/Private/Components/Templates/Events/'
  events.partialRootPath:
    label: 'Partials'
    category: Events.templates
    description: 'Path to partial root'
    type: string
    default: 'EXT:sitepackage/Resources/Private/Components/Partials/Events/'
  events.layoutRootPath:
    label: 'Layouts'
    category: Events.templates
    description: 'Path to layout root'
    type: string
    default: 'EXT:sitepackage/Resources/Private/Components/Layouts/Events/'
  events.storagePid:
    label: 'Default storage PID'
    category: Events.pages
    description: 'Folder that stores all blogs, blog-posts and comments'
    type: int
    default: 2
  events.singleViewPageUid:
    label: 'Single view PID'
    category: Events.pages
    description: 'Single view page'
    type: int
    default: 2
