name: mens-circle
type: typo3
docroot: public
php_version: "8.4"
webserver_type: nginx-fpm
database:
  type: mariadb
  version: "11.4"
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
use_dns_when_possible: true
composer_version: "2"
nodejs_version: "22"
corepack_enable: true

web_environment:
  - TYPO3_CONTEXT=Development
  - APP_ENV=development

hooks:
  post-start:
    - exec: "mkdir -p /var/www/html/var/log"
